name: Debug Package Installation

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-packages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libfreetype6-dev \
          libpng-dev \
          libtiff5-dev \
          libjpeg-dev
        
    - name: Install core R packages first
      run: |
        options(repos = c(CRAN = "https://cloud.r-project.org/"))
        install.packages("remotes", dependencies = TRUE)
        install.packages("RCurl", dependencies = TRUE)
        install.packages("readr", dependencies = TRUE)
        install.packages("dplyr", dependencies = TRUE)
        install.packages("lubridate", dependencies = TRUE)
        install.packages("rsconnect", dependencies = TRUE)
      shell: Rscript {0}
      
    - name: Install tidyverse components
      run: |
        options(repos = c(CRAN = "https://cloud.r-project.org/"))
        install.packages(c("ggplot2", "tibble", "tidyr", "purrr", "stringr", "forcats"), dependencies = TRUE)
        install.packages("tidyverse", dependencies = TRUE)
      shell: Rscript {0}
      
    - name: Test loading packages
      run: |
        cat("Testing package loading...\n")
        library(RCurl)
        cat("✅ RCurl loaded\n")
        library(readr)
        cat("✅ readr loaded\n")
        library(dplyr)
        cat("✅ dplyr loaded\n")
        library(lubridate)
        cat("✅ lubridate loaded\n")
        library(tidyverse)
        cat("✅ tidyverse loaded\n")
        library(rsconnect)
        cat("✅ rsconnect loaded\n")
        cat("🎉 All packages loaded successfully!\n")
      shell: Rscript {0}
      
    - name: Test basic script functionality
      run: |
        cat("Testing basic script functions...\n")
        library(tidyverse)
        test_data <- tibble(
          PitcherTeam = c("VIR_KEY", "OTHER_TEAM", "VIR_KEY"),
          BatterTeam = c("OTHER_TEAM", "VIR_KEY", "ANOTHER_TEAM")
        )
        vmi_data <- test_data %>%
          filter(PitcherTeam %in% c("VIR_KEY", "VMI_KEY") | BatterTeam %in% c("VIR_KEY", "VMI_KEY"))
        cat("Test filtering result:", nrow(vmi_data), "rows (should be 3)\n")
        if (nrow(vmi_data) == 3) {
          cat("✅ Filtering logic works!\n")
        } else {
          cat("❌ Filtering logic failed!\n")
        }
      shell: Rscript {0}
